import type { Metadata } from "next";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import { ReactNode } from "react";
import UIProvider from "@/lib/Provider";

export const metadata: Metadata = {
  title: "PoshFoods-Bangladesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UIProvider>
          <div className="dark text-foreground bg-background">{children}</div>
        </UIProvider>
      </body>
      <ToastContainer />
    </html>
  );
}
