import type { Metadata } from "next";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import { ReactNode } from "react";
import UIProvider from "@/lib/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <UIProvider>
        <body>{children}</body>
      </UIProvider>
      <ToastContainer />
    </html>
  );
}
